import { ENVIRONMENT } from '../../../../env';

export const AdapterConfigure = {
  AUTHBASIC: ENVIRONMENT.INSPIREHUB_FASTLINK.AUTHBASIC,
  URL: ENVIRONMENT.INSPIREHUB_FASTLINK.URL,
  SCHEMA: ENVIRONMENT.INSPIREHUB_FASTLINK.SCHEMA,
  ENTITY: ENVIRONMENT.INSPIREHUB_FASTLINK.ENTITY,
  SCHEMA_DESC: ENVIRONMENT.INSPIREHUB_FASTLINK.SCHEMA_DESC,
  ENTITY_DESC: ENVIRONMENT.INSPIREHUB_FASTLINK.ENTITY_DESC,
};
