import { ENVIRONMENT } from '../../../../env';

export const AdapterConfigure = {
  SCHEMA_CREATESPACE: ENVIRONMENT.INSPIREHUB_GAMES.SCHEMA,
  SCHEMA: ENVIRONMENT.INSPIREHUB_GAMESTETRIS.SCHEMA,
  ENTITY: ENVIRONMENT.INSPIREHUB_GAMESTETRIS.ENTITY,
  SCHEMA_DESC: ENVIRONMENT.INSPIREHUB_GAMESTETRIS.SCHEMA_DESC,
  ENTITY_DESC: ENVIRONMENT.INSPIREHUB_GAMESTETRIS.ENTITY_DESC,
};
