import { ENVIRONMENT } from '../../../../env';

export const AdapterConfigure = {
  SCHEMA: ENVIRONMENT.INSPIREHUB_GAMES.SCHEMA,
  ENTITY: ENVIRONMENT.INSPIREHUB_GAMES.ENTITY,
  SCHEMA_DESC: ENVIRONMENT.INSPIREHUB_GAMES.SCHEMA_DESC,
  ENTITY_DESC: ENVIRONMENT.INSPIREHUB_GAMES.ENTITY_DESC,
};
