import { ENVIRONMENT } from '../../../../env';

export const AdapterConfigure = {
  AUTHBASIC: ENVIRONMENT.INSPIREHUB_FASTLINK.AUTHBASIC,
  URL: ENVIRONMENT.INSPIREHUB_FASTLINK.URL,
  SCHEMA: ENVIRONMENT.MASTER_CONTACTMESSAGE.SCHEMA,
  ENTITY: ENVIRONMENT.MASTER_CONTACTMESSAGE.ENTITY,
};
