import { ENVIRONMENT } from '../../../../env';

export const AdapterConfigure = {
  SCHEMA_CREATESPACE: ENVIRONMENT.INSPIREHUB_GAMES.SCHEMA,
  SCHEMA: ENVIRONMENT.INSPIREHUB_GAMESPONG.SCHEMA,
  ENTITY: ENVIRONMENT.INSPIREHUB_GAMESPONG.ENTITY,
  SCHEMA_DESC: ENVIRONMENT.INSPIREHUB_GAMESPONG.SCHEMA_DESC,
  ENTITY_DESC: ENVIRONMENT.INSPIREHUB_GAMESPONG.ENTITY_DESC,
};