import { ENVIRONMENT } from '../../../../env';

export const AdapterConfigure = {
  SCHEMA_CREATESPACE: ENVIRONMENT.INSPIREHUB_GAMES.SCHEMA,
  SCHEMA: ENVIRONMENT.INSPIREHUB_GAMES2048.SCHEMA,
  ENTITY: ENVIRONMENT.INSPIREHUB_GAMES2048.ENTITY,
  SCHEMA_DESC: ENVIRONMENT.INSPIREHUB_GAMES2048.SCHEMA_DESC,
  ENTITY_DESC: ENVIRONMENT.INSPIREHUB_GAMES2048.ENTITY_DESC,
};