import { ENVIRONMENT } from '../../../../env';

export const AdapterConfigure = {
  SCHEMA_CREATESPACE: ENVIRONMENT.INSPIREHUB_GAMES.SCHEMA,
  SCHEMA: ENVIRONMENT.INSPIREHUB_GAMESSNAKE.SCHEMA,
  ENTITY: ENVIRONMENT.INSPIREHUB_GAMESSNAKE.ENTITY,
  SCHEMA_DESC: ENVIRONMENT.INSPIREHUB_GAMESSNAKE.SCHEMA_DESC,
  ENTITY_DESC: ENVIRONMENT.INSPIREHUB_GAMESSNAKE.ENTITY_DESC,
};
