import { ENVIRONMENT } from '../../../../env';

export const AdapterConfigure = {
  AUTHBASIC: ENVIRONMENT.INSPIREHUB_FASTLINK.AUTHBASIC,
  URL: ENVIRONMENT.INSPIREHUB_FASTLINK.URL,
  SCHEMA: ENVIRONMENT.INSPIREHUB_GAMES.SCHEMA,
  ENTITY: ENVIRONMENT.INSPIREHUB_GAMES.ENTITY,
};
